### ISSUE TITLE
Setting Cell Level CSS (background color) from SQL Query.

### ISSUE THREAD

**Issue by DougAGault** [plug-ins-pro/enhanced_grid_pro#3]
My goal is to set the rendered background color of a specific cell based on logic in the SQL, and not to have to do it as a “second pass” using `ucGrid.addCssClass` after the initial grid has been rendered.

For each column exposed under the plugin in the builder there is a `CSS Classes` attribute under the Appearance section of the Attributes Tab.  If I reference the value of a hidden column from my SQL query (that dictates the CSS class name I want to apply), I would have expected it to be **_dynamically_** applied to each cell rendered for that column in the report . However,  the plugin seems to be ignoring this attribute all together.

Am I missing what this setting should be used for? Is there a way to do this from the SQL, or am I forced to do the coloration of cells after the grid has rendered? 
Thanks in advance.

**Comment by andraz-podobnik** [comment]
Hi,

you are right, `CSS Classes` attribute under "Appearance" section was ignored.
With Enhanced Grid Pro version 23.2, this will be fixed.

As you wrote, you will be able to reference the value of a hidden column from SQL query. Like this:
`#COL_NAME#`

Maybe you can ask Jackie/Dimitri for another Beta before the v23.2 gets released (just to make sure it works for you).

Thanks,
Andraz

**Comment by DougAGault** [comment]
Got the beta from the team and everything works as expected. 

Thanks again for the quick turn around!
